spring.datasource.url= jdbc:postgresql://localhost:5432/projeto_springSecurity_JWT
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

jwt.public.key=classpath:public.key
jwt.private.key=classpath:private.key